Allow you to get the layername you are on.
FrederoxDev/Amethyst pull request #39
Opened 2024-01-17 01:52 UTC by notchyves

Basically, if you are on chest screen the layer name will tell you "chest_screen", basically this is just a useful utilit.y

2024-01-17 02:01 UTC, ZeroMemes commented on AmethystAPI/src/amethyst/Memory.h
> +Ret& direct_access(Type* type, size_t offset) {
The returned type should have the constness of `Type`

2024-01-17 02:06 UTC, ZeroMemes commented
This method only works for `UIScene` derived screens (which actually contain a `std::unique_ptr<ScreenView>`).

A much simpler approach is to call the `AbstractScene::getScreenName` virtual function.

2024-01-17 07:26 UTC, FrederoxDev commented
Thanks, as a general rule, this project has been defining memory layouts of classes, because it makes it easier to understand the class, and easier to preview the structures size and layout with tooling. Im not completely against having a build access macro for testing, but I don't think it should be in final committed code if that makes sense

2024-01-17 08:13 UTC, ZeroMemes requested changes
:(

2024-01-17 08:13 UTC, ZeroMemes commented on AmethystAPI/src/amethyst/Memory.h
> +	type get##name() const { return direct_access<type>(ptr, offset); } \
just noticed this now... this should return a reference to type, otherwise unnecessary copies are being created. seems extremely bug prone.

2024-01-17 08:13 UTC, ZeroMemes commented on AmethystAPI/src/amethyst/Memory.h
> +	void set##name(type v) const { direct_access<type>(ptr, offset) = v; }
assignment should be `= std::move(v);`

2024-01-17 08:13 UTC, ZeroMemes commented on AmethystAPI/src/amethyst/Memory.h
> +	type get##name()
same as below.. should return a ref

2024-01-17 08:18 UTC, FrederoxDev requested changes
See Brady's suggested changes

2024-01-17 23:34 UTC, notchyves reviewed
Done!

2024-01-17 23:42 UTC, FrederoxDev requested changes

2024-01-17 23:42 UTC, FrederoxDev commented on AmethystAPI/src/minecraft/src-client/common/client/gui/ScreenView.h
> +    BUILD_ACCESS(this, class VisualTree*, VisualTree, 0x48);
This should be replaced with an actual field in the struct, see: https://github.com/FrederoxDev/Amethyst/pull/39#issuecomment-1895228515

2024-01-17 23:42 UTC, FrederoxDev commented on AmethystAPI/src/minecraft/src-client/common/client/gui/gui/VisualTree.h
> +    BUILD_ACCESS(this, class UIControl*, root, 0x8);
This should be replaced with an actual field in the struct, see: https://github.com/FrederoxDev/Amethyst/pull/39#issuecomment-1895228515

2024-01-17 23:42 UTC, FrederoxDev commented on AmethystAPI/src/minecraft/src-client/common/client/gui/gui/UIControl.h
> +  BUILD_ACCESS(this, std::string, layerName, 0x18);
This should be replaced with an actual field in the struct, see: https://github.com/FrederoxDev/Amethyst/pull/39#issuecomment-1895228515

2024-01-17 23:42 UTC, FrederoxDev commented on AmethystAPI/src/amethyst/Memory.h
> +direct_access(Type* type, size_t offset) {
For naming consistency in the project, we are following PascalCase, `direct_access` would be better as `DirectAccess`

2024-01-18 00:51 UTC, FrederoxDev commented
This is the standard of code that I am using in this project, updating isn't a thing this project will do, except for major version releases. It takes an insignificant amount of time to just write a the member variables, there are even tools you can use to help you do this too.

2024-01-18 19:55 UTC, Intoprelised commented
no offense but asm is right, then you gotta updated the comments too and all the padding

2024-01-18 19:55 UTC, Intoprelised commented
and like not even just updating but if you wanna add a member like in between 2 members that already exist u gotta recalculate the padding

2024-01-18 20:08 UTC, FrederoxDev commented
I have to be honest, its not a particularly hard thing to do, nor does it take more than a minute. You can use tools like: https://github.com/Viladoman/StructLayout which allow you to preview the sizes and positions.

2024-01-18 20:09 UTC, Intoprelised commented
thoughts on making it as easy as possible?

2024-01-18 20:12 UTC, ZeroMemes commented
Forced to use Visual Studio

![](https://media.tenor.com/izTNkY2BgkAAAAAM/fade-away-oooooooooooo.gif)

2024-01-18 20:34 UTC, riesters commented
"screenview->visualtree->root->layername" this is dumb.
May I suggest"screenview->visualtree->chickenbutt"?

2024-01-18 22:51 UTC, Intoprelised commented
🤬

2024-01-18 23:13 UTC, FrederoxDev approved these changes

2024-01-18 23:14 UTC, merged